import { test, expect } from '@playwright/test';

const summary={recent_runs:1,pending:1,ambiguous:1,conflicts:0,to_validate:1,validated:0,rejected:0,deferred:0};
const review={candidate_id:'CAN-SYNTHETIC',review_id:'REV-SYNTHETIC',decision_id:'DEC-SYNTHETIC',source_name:'CENI_SYNTHETIC',source_entity_id:'SRC-1',target_name:'EDUCATION_SYNTHETIC',target_entity_id:'TGT-1',score:62,confidence:.74,ambiguity:'HIGH',engine_decision:'AMBIGUOUS',status:'PENDING',created_at:'2026-07-18T12:00:00Z',priority:1,requires_human_review:true};
const dossier={candidate:{...review,status:'AMBIGUOUS',explanation:'Explication synthétique persistée.'},source_entity:{entity_type:'SCHOOL',attributes:{name:'EP TEST',normalized_name:'EP TEST',latitude:-4.3,longitude:15.3,province:'KINSHASA'}},target_entity:{entity_type:'SCHOOL',attributes:{name:'EP TEST B',normalized_name:'EP TEST',latitude:-4.31,longitude:15.31,province:'KINSHASA'}},evidences:[{evidence_id:'E1',evidence_type:'NORMALIZED_NAME',value:'EP TEST',weight:25,confidence:.9,reliability:.9,payload:{status:'SUPPORTING',method:'synthetic',extractor_version:'test'}}],decision:{decision_id:'DEC-SYNTHETIC',decision:'AMBIGUOUS',explanation:'Explication synthétique persistée.',engine_version:'test',rule_version:'test'},review,blocking_conflicts:[],ambiguity:'HIGH'};

async function mockNire(page){
  await page.route('**/api/nire/**',async route=>{const url=route.request().url();let body={};if(url.includes('/workspace/summary'))body=summary;else if(url.includes('/review-dossiers'))body={offset:0,limit:25,items:[review]};else if(url.includes('/dossier'))body=dossier;else if(url.includes('/history'))body={items:[{date:'2026-07-18',action:'AMBIGUOUS',author:'SYSTEM',old_value:null,new_value:'AMBIGUOUS',justification:'Synthétique'}]};else if(url.includes('/roles'))body={role:route.request().headers()['x-nire-role']||'ANALYST',actions:['VIEW','PREPARE','DEFER'],contract_version:'test'};else if(url.includes('/mno-audit/status'))body={executed:false,source_loaded:false,operators:[],message:'Aucun audit MNO n’a encore été exécuté. Chargez une source MNO validée pour démarrer une analyse.'};else if(url.includes('/runs'))body={offset:0,limit:25,items:[]};else body={status:'DEFERRED'};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});});
}

test('Dashboard initial ne charge ni API ni asset NIRE',async({page})=>{const requests=[];page.on('request',r=>requests.push(r.url()));await page.goto('http://127.0.0.1:8000/#dashboard');await page.waitForTimeout(500);expect(requests.filter(u=>u.includes('/api/nire')||u.includes('nire-workspace.js'))).toEqual([]);});
test('workspace lazy-loaded et KPI agrégés',async({page})=>{await mockNire(page);await page.goto('http://127.0.0.1:8000/#dashboard');await page.getByText('Résolution d’identité',{exact:true}).click();await expect(page.getByRole('heading',{name:/Résolution d’identité/})).toBeVisible();await expect(page.getByText('Candidats en attente')).toBeVisible();});
test('file paginée, filtres et dossier côte à côte',async({page})=>{await mockNire(page);await page.goto('http://127.0.0.1:8000/#nire-workspace');await page.getByRole('button',{name:'File de revue'}).click();await page.getByRole('button',{name:'Ouvrir'}).click();await expect(page.getByText('Entité source')).toBeVisible();await expect(page.getByText('Candidat cible')).toBeVisible();await expect(page.locator('#nire-map')).toBeVisible();});
test('preuves, décision persistée et historique',async({page})=>{await mockNire(page);await page.goto('http://127.0.0.1:8000/#nire-workspace');await page.getByRole('button',{name:'File de revue'}).click();await page.getByRole('button',{name:'Ouvrir'}).click();await expect(page.getByText('Preuves positives')).toBeVisible();await expect(page.getByText('Explication synthétique persistée.').first()).toBeVisible();await expect(page.getByText('Historique complet')).toBeVisible();});
test('Audit MNO reste vide sans chiffre fictif',async({page})=>{await mockNire(page);await page.goto('http://127.0.0.1:8000/#nire-workspace');await page.getByRole('button',{name:'Audit MNO'}).click();await expect(page.getByText(/Aucun audit MNO/)).toBeVisible();await expect(page.getByText(/Non calculé — aucune source MNO validée/).first()).toBeVisible();});
