"""NIRE Phase 3 operational persistence

Revision ID: 0006_nire_operational
Revises: 0005_cnct_knowledge_base
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0006_nire_operational"; down_revision="0005_cnct_knowledge_base"; branch_labels=None; depends_on=None
SCHEMA="nire"
def upgrade():
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")
    op.create_table("resolution_runs",sa.Column("run_id",sa.String(64),primary_key=True),sa.Column("idempotency_key",sa.String(200),nullable=False,unique=True),sa.Column("source_name",sa.String(100),nullable=False),sa.Column("target_name",sa.String(100),nullable=False),sa.Column("engine_version",sa.String(80),nullable=False),sa.Column("rule_version",sa.String(80),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("batch_size",sa.Integer,nullable=False),sa.Column("max_candidates",sa.Integer,nullable=False),sa.Column("timeout_seconds",sa.Integer,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),schema=SCHEMA)
    op.create_table("resolution_candidates",sa.Column("candidate_id",sa.String(64),primary_key=True),sa.Column("run_id",sa.String(64),sa.ForeignKey(f"{SCHEMA}.resolution_runs.run_id"),nullable=False),sa.Column("source_name",sa.String(100),nullable=False),sa.Column("source_entity_id",sa.String(200),nullable=False),sa.Column("target_name",sa.String(100),nullable=False),sa.Column("target_entity_id",sa.String(200),nullable=False),sa.Column("score",sa.Float,nullable=False),sa.Column("confidence",sa.Float,nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("explanation",sa.Text,nullable=False),sa.Column("requires_human_review",sa.Boolean,nullable=False,server_default=sa.true()),sa.Column("payload",postgresql.JSONB,nullable=False,server_default="{}"),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),schema=SCHEMA)
    op.create_index("ix_nire_candidates_source","resolution_candidates",["source_name","source_entity_id"],schema=SCHEMA)
    op.create_table("resolution_evidences",sa.Column("evidence_id",sa.String(64),primary_key=True),sa.Column("candidate_id",sa.String(64),sa.ForeignKey(f"{SCHEMA}.resolution_candidates.candidate_id"),nullable=False),sa.Column("evidence_type",sa.String(100),nullable=False),sa.Column("source_name",sa.String(100),nullable=False),sa.Column("source_entity_id",sa.String(200),nullable=False),sa.Column("value",postgresql.JSONB),sa.Column("weight",sa.Float,nullable=False),sa.Column("confidence",sa.Float,nullable=False),sa.Column("reliability",sa.Float,nullable=False),sa.Column("payload",postgresql.JSONB,nullable=False,server_default="{}"),schema=SCHEMA)
    op.create_table("resolution_decisions",sa.Column("decision_id",sa.String(64),primary_key=True),sa.Column("candidate_id",sa.String(64),sa.ForeignKey(f"{SCHEMA}.resolution_candidates.candidate_id"),nullable=False),sa.Column("decision",sa.String(50),nullable=False),sa.Column("score",sa.Float,nullable=False),sa.Column("engine_version",sa.String(80),nullable=False),sa.Column("rule_version",sa.String(80),nullable=False),sa.Column("explanation",sa.Text,nullable=False),sa.Column("previous_decision_id",sa.String(64),sa.ForeignKey(f"{SCHEMA}.resolution_decisions.decision_id")),sa.Column("cancelled_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),schema=SCHEMA)
    op.create_table("review_queue",sa.Column("review_id",sa.String(64),primary_key=True),sa.Column("candidate_id",sa.String(64),sa.ForeignKey(f"{SCHEMA}.resolution_candidates.candidate_id"),nullable=False),sa.Column("decision_id",sa.String(64),sa.ForeignKey(f"{SCHEMA}.resolution_decisions.decision_id"),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("priority",sa.Integer,nullable=False,server_default="0"),sa.Column("assigned_to",sa.String(200)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),schema=SCHEMA)
    op.create_index("ix_nire_review_status","review_queue",["status","priority"],schema=SCHEMA)
    op.create_table("review_actions",sa.Column("action_id",sa.String(64),primary_key=True),sa.Column("review_id",sa.String(64),sa.ForeignKey(f"{SCHEMA}.review_queue.review_id"),nullable=False),sa.Column("action",sa.String(30),nullable=False),sa.Column("author",sa.String(200),nullable=False),sa.Column("role",sa.String(30),nullable=False),sa.Column("justification",sa.Text,nullable=False),sa.Column("evidence_ids",postgresql.ARRAY(sa.String),nullable=False),sa.Column("previous_status",sa.String(30),nullable=False),sa.Column("new_status",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),schema=SCHEMA)
    op.create_table("rule_versions",sa.Column("version",sa.String(80),primary_key=True),sa.Column("document",postgresql.JSONB,nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("active",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),schema=SCHEMA)
    op.create_table("decision_history",sa.Column("history_id",sa.String(64),primary_key=True),sa.Column("decision_id",sa.String(64),sa.ForeignKey(f"{SCHEMA}.resolution_decisions.decision_id"),nullable=False),sa.Column("old_decision",sa.String(50)),sa.Column("new_decision",sa.String(50),nullable=False),sa.Column("author",sa.String(200),nullable=False),sa.Column("reason",sa.Text,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),schema=SCHEMA)
def downgrade():
    op.drop_table("decision_history",schema=SCHEMA); op.drop_table("rule_versions",schema=SCHEMA); op.drop_table("review_actions",schema=SCHEMA); op.drop_index("ix_nire_review_status",table_name="review_queue",schema=SCHEMA); op.drop_table("review_queue",schema=SCHEMA); op.drop_table("resolution_decisions",schema=SCHEMA); op.drop_table("resolution_evidences",schema=SCHEMA); op.drop_index("ix_nire_candidates_source",table_name="resolution_candidates",schema=SCHEMA); op.drop_table("resolution_candidates",schema=SCHEMA); op.drop_table("resolution_runs",schema=SCHEMA); op.execute(f"DROP SCHEMA IF EXISTS {SCHEMA}")
