ALTER TABLE zones ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;
ALTER TABLE provinces ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;
ALTER TABLE territoires ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;
ALTER TABLE villes ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;
ALTER TABLE collectivites ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;
ALTER TABLE groupements ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;
ALTER TABLE localites ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;
ALTER TABLE sites ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;
ALTER TABLE missions ADD COLUMN IF NOT EXISTS altitude DOUBLE PRECISION;

